### ISSUE TITLE
MacOS Intellij idea 中，始终无法 Add MaxCompute Project

### ISSUE THREAD

**Issue by Char-CN** [aliyun/aliyun-odps-console#3]
Add MaxCompute Project时，选择odps_config.ini
会出现一个红色的错误提示：
Test connection fail: Can't bind xml to class com.aliyun.odps.Project$ProjectModel

以下是idea.log

`2018-01-15 18:09:56,910 [ 934597]   WARN - studio.component.util.OdpsUtil - [MaxCompute STUDIO]test project access fail
com.aliyun.odps.OdpsException: Can't bind xml to class com.aliyun.odps.Project$ProjectModel
	at com.aliyun.odps.Project.reload(Project.java:232)
	at com.aliyun.odps.studio.component.util.OdpsUtil.testOdps(OdpsUtil.java:165)
	at com.aliyun.odps.studio.project.explorer.OdpsProjectConfigPanel.getProjectAccess(OdpsProjectConfigPanel.java:276)
	at com.aliyun.odps.studio.project.explorer.OdpsProjectConfigPanel.updateAccessProperties(OdpsProjectConfigPanel.java:258)
	at com.aliyun.odps.studio.project.explorer.OdpsProjectConfigPanel.access$100(OdpsProjectConfigPanel.java:42)
	at com.aliyun.odps.studio.project.explorer.OdpsProjectConfigPanel$1.insertUpdate(OdpsProjectConfigPanel.java:224)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
	at com.intellij.ui.components.JBTextField.setText(JBTextField.java:62)
	at com.intellij.openapi.ui.TextComponentAccessor$1.setText(TextComponentAccessor.java:44)
	at com.intellij.openapi.ui.TextComponentAccessor$1.setText(TextComponentAccessor.java:36)
	at com.intellij.openapi.ui.ComponentWithBrowseButton$BrowseFolderActionListener.onFileChosen(ComponentWithBrowseButton.java:305)
	at com.intellij.openapi.fileChooser.FileChooser.lambda$chooseFile$0(FileChooser.java:151)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:174)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:114)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFile(FileChooser.java:151)
	at com.intellij.openapi.ui.ComponentWithBrowseButton$BrowseFolderActionListener.actionPerformed(ComponentWithBrowseButton.java:269)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:734)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:456)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1696)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1645)
	at com.intellij.openapi.ui.DialogBuilder.showImpl(DialogBuilder.java:88)
	at com.intellij.openapi.ui.DialogBuilder.show(DialogBuilder.java:55)
	at com.aliyun.odps.studio.intellij.project.OdpsProjectConfigurationForm.getProject(OdpsProjectConfigurationForm.java:46)
	at com.aliyun.odps.studio.intellij.project.ProjectExplorerWindow.getProjectInfoFromUserInput(ProjectExplorerWindow.java:209)
	at com.aliyun.odps.studio.project.explorer.ProjectExplorer.addNewProject(ProjectExplorer.java:127)
	at com.aliyun.odps.studio.project.explorer.ProjectExplorer.addNewProject(ProjectExplorer.java:135)
	at com.aliyun.odps.studio.project.explorer.ProjectExplorer$1.actionPerformed(ProjectExplorer.java:87)
	at com.aliyun.odps.studio.intellij.component.control.ActionAdapter$1.actionPerformed(ActionAdapter.java:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:193)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:344)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at com.aliyun.odps.commons.util.DateUtils.parseRfc822Date(DateUtils.java:307)
	at com.aliyun.odps.Project.reload(Project.java:224)
	... 112 more`

**Comment by Char-CN** [comment]
尝试过的解决方案：
1.重装MaxCompute Plug
2.重装Intellij Idea 
3.清楚该用户下的插件缓存：https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by Char-CN** [comment]
删除Max Compute Plugin的时候错误日志：
`2018-01-15 18:29:11,445 [   2882]   WARN - s.studio.option.ManageSettings - [MaxCompute STUDIO]fail to query manage settings from server
java.io.IOException: Server returned HTTP response code: 502 for URL: http://odps.alibaba.net:8080/studio-service/setting?version=2.8.2.1
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.aliyun.odps.studio.ide.MyHttpClient.doGetString(MyHttpClient.java:56)
	at com.aliyun.odps.studio.option.ManageSettings.isEnableDebugger(ManageSettings.java:32)
	at com.aliyun.odps.studio.intellij.StudioMain$2.run(StudioMain.java:122)`

**Comment by lyman** [comment]
endpoint 配错了吧？

**Comment by Char-CN** [comment]
没有啊，默认的，和同事的一样。

**Comment by Char-CN** [comment]
![1111111111111111](https://user-images.githubusercontent.com/4012897/34939318-585fef94-fa26-11e7-8d2a-c833cd376d1c.png)

**Comment by yigeliuyi** [comment]
检查connection联通性报错了，一般可能是odps_config.ini里endpoint配置错了

**Comment by guozhenhong** [comment]
检查下机器是否开了 vpn 代理程序。
如果有 vpn, 即使在 disconnect 状态，请退出代理服务再试下。

**Comment by Char-CN** [comment]
感谢 @guozhenhong ，感谢各位，确实VPN的问题。现在解决了。
