### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by chenwentest** [aliyun/aliyun-odps-console#32]
Exception in thread "main" java.lang.NoClassDefFoundError: com/aliyun/odps/compiler/parser/OdpsLexer
	at com.aliyun.odps.sqa.commandapi.utils.SqlParserUtil.getSqlParserListener(SqlParserUtil.java:208)
	at com.aliyun.odps.sqa.commandapi.utils.SqlParserUtil.isSelect(SqlParserUtil.java:175)
	at com.aliyun.odps.sqa.SQLExecutorImpl.isSelect(SQLExecutorImpl.java:1347)
	at com.aliyun.odps.sqa.SQLExecutorImpl.getResultSetInternal(SQLExecutorImpl.java:1013)
	at com.aliyun.odps.sqa.SQLExecutorImpl.getResultSet(SQLExecutorImpl.java:667)
	at com.aliyun.openservices.odps.console.InteractiveQueryCommand.getQueryResult(InteractiveQueryCommand.java:305)
	at com.aliyun.openservices.odps.console.InteractiveQueryCommand.submitSubQuery(InteractiveQueryCommand.java:370)
	at com.aliyun.openservices.odps.console.InteractiveQueryCommand.run(InteractiveQueryCommand.java:694)
	at com.aliyun.openservices.odps.console.commands.AbstractCommand.execute(AbstractCommand.java:116)
	at com.aliyun.openservices.odps.console.commands.InteractiveCommand.run(InteractiveCommand.java:108)
	at com.aliyun.openservices.odps.console.commands.AbstractCommand.execute(AbstractCommand.java:116)
	at com.aliyun.openservices.odps.console.commands.CompositeCommand.run(CompositeCommand.java:48)
	at com.aliyun.openservices.odps.console.commands.AbstractCommand.execute(AbstractCommand.java:116)
	at com.aliyun.openservices.odps.console.ODPSConsole.main(ODPSConsole.java:63)
Caused by: java.lang.ClassNotFoundException: com.aliyun.odps.compiler.parser.OdpsLexer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more

**Comment by galeka** [comment]
My java version
% java -version               
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

I got same error when run "mvn clean test"
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/3ac17dee-7243-436a-83e4-7e4b680d2936">
[ERROR] Errors: 
[ERROR]   InstanceRunnerTest.<clinit>:67 » NoClassDefFound Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
[ERROR]   InstanceRunnerTest.testPollingOutput » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest
[ERROR]   InstanceRunnerTest.testSubmitRetry_failed » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest
[ERROR]   InstanceRunnerTest.testSubmitRetry_listFailed » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest
[ERROR]   InstanceRunnerTest.testSubmitRetry_listSuccess » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest
[ERROR]   InstanceRunningTest.testInstanceRunning_GetProgressFail » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.output.state.InstanceRunningTest
[ERROR]   InstanceRunningTest.<clinit>:39 » ExceptionInInitializer
[ERROR]   ODPSConsoleUtilsTest.getConfigNull:50 ClassCast class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
[INFO] 
[ERROR] Tests run: 51, Failures: 0, Errors: 8, Skipped: 0

**Comment by dingxin-tech** [comment]
> My java version % java -version openjdk version "21.0.2" 2024-01-16 LTS OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)
> 
> I got same error when run "mvn clean test" <img alt="image" width="1419" src="https://private-user-images.githubusercontent.com/75578995/358921432-3ac17dee-7243-436a-83e4-7e4b680d2936.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzE3NzcsIm5iZiI6MTcyNDAzMTQ3NywicGF0aCI6Ii83NTU3ODk5NS8zNTg5MjE0MzItM2FjMTdkZWUtNzI0My00MzZhLTgzZTQtN2U0YjY4MGQyOTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxMzc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNDIzYjZlYzM0NGU2Mjg4MGM2NWI0ODYzODA5OTIyNTE1ZGQ4YWVhNTU2ZTkyN2EzMzc4ZGUzNjUyMDM4MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNDvVgCuWBMiHUkEgenYDs0eTafY-jFy_nrQtd20rpA"> [ERROR] Errors: [ERROR] InstanceRunnerTest.:67 » NoClassDefFound Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3 [ERROR] InstanceRunnerTest.testPollingOutput » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest [ERROR] InstanceRunnerTest.testSubmitRetry_failed » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest [ERROR] InstanceRunnerTest.testSubmitRetry_listFailed » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest [ERROR] InstanceRunnerTest.testSubmitRetry_listSuccess » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.InstanceRunnerTest [ERROR] InstanceRunningTest.testInstanceRunning_GetProgressFail » NoClassDefFound Could not initialize class com.aliyun.openservices.odps.console.output.state.InstanceRunningTest [ERROR] InstanceRunningTest.:39 » ExceptionInInitializer [ERROR] ODPSConsoleUtilsTest.getConfigNull:50 ClassCast class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') [INFO] [ERROR] Tests run: 51, Failures: 0, Errors: 8, Skipped: 0

Hi @galeka,

The error you are seeing (java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader) is due to the changes in Java 9 where application and extension classes are no longer instances of java.net.URLClassLoader. This causes issues when using reflection operations.

Specifically, the problem arises from using Mockito v1, which is not compatible with JDK versions higher than Java 8. Unfortunately, our test suite is currently built on JDK 8. We will work on adapting and upgrading our test suite to accommodate higher JDK versions in the future.

Thank you for bringing this to our attention and we apologize for any inconvenience this has caused. If you have any further questions or concerns, please feel free to reach out.

Best, @dingxin-tech
